- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
- name: Install Docker
  apt:
    name: docker-ce=5:19.03.7~3-0~ubuntu-bionic
    state: present
    update_cache: yes
- name: Install Docker Compose
  vars:
    version: 1.25.4
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ version }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
- name: /etc/docker/daemon.json
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  register: docker_daemon_json
- name: Restart docker daemon
  service:
    name: docker
    state: restarted
  when: docker_daemon_json.changed